SELECT * FROM ITENS_NOTAS_FISCAIS
SELECT * FROM NOTAS_FISCAIS
SELECT * FROM TABELA_DE_CLIENTES
SELECT * FROM TABELA_DE_PRODUTOS
SELECT * FROM TABELA_DE_PRODUTOS



SELECT
	CLI.CPF, 
	CLI.NOME, 
	CLI.VOLUME_DE_COMPRA,
	CONVERT(VARCHAR(7), NF.DATA_VENDA, 120) AS "MÊS E ANO",
	SUM(INF.QUANTIDADE) AS "SOMA DAS QUANTIDADES"
FROM
TABELA_DE_CLIENTES CLI
INNER JOIN NOTAS_FISCAIS NF
ON CLI.CPF = NF.CPF
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON INF.NUMERO = NF.NUMERO
GROUP BY CLI.CPF, CLI.NOME, CLI.VOLUME_DE_COMPRA, CONVERT(VARCHAR(7), NF.DATA_VENDA, 120)
